### PR TITLE
Replaced the hyphen literal in track content with the HTML entity of …

### PR DESCRIPTION
**Pull request by ElishebaW**
…a hyphen'

References: #106

The strange characters appear in Chrome and Firefox as well. The issue is there was an actual hyphen included in the code. I updated it to an HTML entity with the spaces entities and it cleared up the issue. 

https://www.w3schools.com/html/html_entities.asp

### CODE REVIEW

**Comment by rwieruch** [comment]
Oh, great find! Thank you again @ElishebaW 💯

**Comment by ElishebaW** [comment]
Hey @rwieruch, do you know why my changes don't appear on the main site? It is http://www.favesound.de/ right?

**Comment by rwieruch** [comment]
I didn't had the chance yet to redeploy the new version :)

**Comment by ElishebaW** [comment]
👍

**Pull request merged**
