### PR TITLE
Adds repeat song feature to player

### PR DESCRIPTION
**Pull request by gokulchandra**
Repeat song Feature on the Nav bar.
#68

### CODE REVIEW

**Comment by rwieruch** [comment]
Thank you @gokulchandra 🎉 Any chance that someone else wants to give his/her first review on this PR? You would have to checkout the branch by gokulchandra:repeat-song-feature and verify that the new functionality works and nothing else breaks.

**Comment by zachyam** [comment]
@rwieruch I can review this PR. What is the process like apart from manually verifying the new functionality and ensuring nothing else breaks?

**Comment by rwieruch** [comment]
@zyam that's the process right now 😅  I would love to have tests for it at some point, but I guess that's another step.

**Comment by gokulchandra** [comment]
Any updates on this PR? It has been a while. 😅

**Comment by chriszhangusc** [comment]
If nobody is reviewing it, I'll do it.

**Comment by chriszhangusc** [comment]
@gokulchandra Sorry for the late review, everything works perfectly fine, well done!

**Comment by rwieruch** [comment]
Good job @gokulchandra @MiniPekka 💯 👍

**Pull request merged**
