### PR TITLE
Fix react hot loader and create babel config file

### PR DESCRIPTION
**Pull request by chriszhangusc**
1. Fixed react-hot-loader for #101.
2. Put babel config into the .babelrc file. #100

### CODE REVIEW

**Comment by rwieruch** [comment]
LGTM. Great change. Hot reloading works with reducers now as well? 🎉

**Comment by chriszhangusc** [comment]
I just test it again and there is something wrong with the reducer hot reloading. I'll review and patch it today.

**Comment by chriszhangusc** [comment]
It should be fine now. I made a silly mistake, should never commit code after 12 am lol.

**Comment by rwieruch** [comment]
What was the mistake?

**Review by rwieruch — APPROVED** [review]

**Comment by chriszhangusc** [comment]
If you look at my last two commits, I missed this line of code "const nextReducer = require('../reducers').default;" which will result in reducer not hot reloading when there are changes.

**Pull request merged**
