### PR TITLE
Fix tooltip display issue in small screen size

### PR DESCRIPTION
**Pull request by chriszhangusc**
#67 Solved by setting the margin left right margin to 10%

### CODE REVIEW

**Comment by chriszhangusc** [comment]
Another way to fix this is that instead of showing a long tooltip, we can just show "Copied". So when there is enough space, it'll be like
screen shot 2017-11-26 at 8 37 31 pm
And when it comes to smaller screen, it will be like
screen shot 2017-11-26 at 8 37 44 pm

Which way do you think is better?

**Comment by rwieruch** [comment]
A shorter text would make sense. Otherwise, I would just merge the PR for now?

**Comment by chriszhangusc** [comment]
I think the shorter text version is better, I'll update the PR.

**Comment by chriszhangusc** [comment]
OK done.

**Pull request merged**
