### PR TITLE
Upgrade to react 16

### PR DESCRIPTION
**Pull request by chriszhangusc**
#69

### CODE REVIEW

**Comment by rwieruch** [comment]
Great @MiniPekka Did you check that the enzyme tests are still running? In the MobX Favesound repository it was a problem. https://github.com/rwieruch/favesound-mobx/issues/14#issuecomment-333385672

**Comment by chriszhangusc** [comment]
@rwieruch Thanks for the heads up, I will fix it right away.

**Comment by chriszhangusc** [comment]
@rwieruch It's OK now. I have upgraded test dependencies for them to play nice with react 16. The issue was mainly caused by enzyme and react 16. 
Also, I have removed chai-enzyme because it does not support enzyme 3.0 and react 16 yet. Here: https://github.com/producthunt/chai-enzyme/issues/199

**Comment by rwieruch** [comment]
Wow, that's awesome @MiniPekka I will update the other PR about your changes (https://github.com/rwieruch/favesound-mobx/issues/14). Maybe we can cross check afterwards both PRs and simply merge them. Thanks again for your work! 🎉

**Comment by chriszhangusc** [comment]
@rwieruch Please don't merge this branch yet, there is a problem caused by the package-lock file generated by npm5. Officially, NPM recommends committing it but it is causing all sorts of unnecessary trouble.  I have created a new PR for this: #72

**Pull request closed without merging**
