### PR TITLE
Fixed waveform errors and not being able to stream errors

### PR DESCRIPTION
**Pull request by chriszhangusc**
Everything seems to be fine by now.

### CODE REVIEW

**Comment by chriszhangusc** [comment]
Question: how do I merge two comments into one? The second commit is not relevant.

**Comment by rwieruch** [comment]
You mean two commits into one? You would've to perform an interactive rebase on the last two commits:

`git rebase -i HEAD~2`

Then you will enter automatically your default editor on the command line (mine is vim). It should look similar to this:

pick b53d5b4
pick a5687fc

You can insert now things by activating the insert mode with `i` when using vim.
Now you can change the last pick to s (= squash). Then the last commit will be merged into the previous one.

pick b53d5b4
s a5687fc

Save and exit the editor on the command line. (:wq <- vim)

That should do the magic. Afterward you have to force push the branch because you changed the history.

`git push -f origin <branch_name>`

But you could leave the two commits as they are :)

**Comment by chriszhangusc** [comment]
@rwieruch I've squashed those two commits together. Thank you so much for your detailed explanation!

**Comment by rwieruch** [comment]
Glad that I can give something in return! Great PR 🎉

**Pull request merged**
